header:
  version: 11

repos:
  openembedded-core:
    url: http://git.openembedded.org/openembedded-core
    commit: e7d3e02a624f7ce23d012bb11ad1df2049066b37
    layers:
      meta:

  bitbake:
    url: http://git.openembedded.org/bitbake
    commit: 907416ee1062f87f5844ab0638b54616abfc1a22
    path: "openembedded-core/bitbake"
    layers:
      bitbake: excluded

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    commit: 346753705e49a2486867dc150181a1c7f4d69377
    layers:
      meta-oe:

local_conf_header:
  base: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    INIT_MANAGER = "systemd"

    # Build info
    INHERIT += "image-buildinfo"

    # Timezone
    DEFAULT_TIMEZONE = "Europe/Paris"

    GLIBC_GENERATE_LOCALES = "fr_FR.UTF-8 en_US.UTF-8"
    IMAGE_LINGUAS = "fr-fr en-us"

    # Python
    IMAGE_INSTALL:append = " python3"
    IMAGE_INSTALL:append = " python3-pip"
    IMAGE_INSTALL:append = " python3-setuptools-scm"

    # Common utilities
    IMAGE_INSTALL:append = " ca-certificates"
    IMAGE_INSTALL:append = " coreutils"
    IMAGE_INSTALL:append = " dynamic-hostname"
    IMAGE_INSTALL:append = " iw"
    IMAGE_INSTALL:append = " nvme-cli"
    IMAGE_INSTALL:append = " os-release"
    IMAGE_INSTALL:append = " p7zip"
    IMAGE_INSTALL:append = " sudo"
    IMAGE_INSTALL:append = " tree"
    IMAGE_INSTALL:append = " tzdata"    

    # Add build infos
    IMAGE_BUILDINFO_VARS:append = " DATETIME DISTRO_NAME IMAGE_BASENAME MACHINE TUNE_PKGARCH" 
    IMAGE_BUILDINFO_VARS:append = " MACHINE_FEATURES DISTRO_FEATURES COMMON_FEATURES IMAGE_FEATURES"
    IMAGE_BUILDINFO_VARS:append = " TUNE_FEATURES TARGET_FPU"
    IMAGE_BUILDINFO_VARS:append = " APP_URI_PREFIX APP_URI_BRANCH"

    # Recipes to ignore
    BBMASK += "/openembedded-core/meta/recipes-sato/*"
