header:
  version: 8

local_conf_header:
  z99-local: |
    DL_DIR     = "/tmp/cache/downloads"
    SSTATE_DIR = "/tmp/cache/sstate-cache"
    TMPDIR     = "#-DIR_DELIVERY-#"
    INHERIT          += "rm_work"
    PARALLEL_MAKE     = "-j20"
    PARALLEL_MAKEINST = "-j20"